### PR TITLE
Arguments checking, helper functions and tests

### LINKED ISSUE #33: Check if parameters are correct
Ex. it's possible to create `Asset` object with incorrect `issuer`.

### PR DESCRIPTION
**Pull request by bartekn**
This PR includes:
- Argument checking for most of the functions + tests (close #33, #35),
- Updated jsdocs for `setOptions` (#35),
- `addMemo` helper function and saving memo to a transaction (#37),
- `import`s from files containing classes not index.js.

### CODE REVIEW

File: src/operation.js [hunk 1]
```diff
@@ -19,15 +23,18 @@ export class Operation {
...
+        if (!isString(opts.startingBalance)) {
+            throw new TypeError('startingBalance argument must be of type String');
+        }
+        if (isEmpty(opts.startingBalance)) {
+            throw new TypeError('startingBalance argument must not be empty');
         }
         let attributes = {};
         attributes.destination  = Keypair.fromAddress(opts.destination).accountId();
-        attributes.startingBalance = Hyper.fromString(String(opts.startingBalance));
+        attributes.startingBalance = Hyper.fromString(opts.startingBalance);
```
Comment (nullstyle) [inline src/operation.js]: Note:  We still haven't updated js-stellar-base to interpret amounts within our conventions for client libraries and horizon (i.e.  7 fixed decimal places)

**Comment by nullstyle** [comment]
Looks great!  :+1:
