### PR TITLE
Encodes the correct field name in the `RevokeLiquidityPoolSponsorship` type

### LINKED ISSUE #502: RevokeLiquidityPoolSponsorship interface returns balanceId instead of liquidityPoolId
**Describe the bug**
TypeScript interface Operation.RevokeLiquidityPoolSponsorship says the operation returns a string called balanceId, it doesn't. It returns a string called liquidityPoolId but TypeScript says no liquidityPoolId exists on that operation due to the bug in the interface.

**What version are you on?**
Stellar-base 7.0.0, stellar-sdk 10.0.0

**Expected behavior**
liquidityPoolId exists on the interface of Operation.RevokeLiquidityPoolSponsorship

**Additional context**
image

### PR DESCRIPTION
**Pull request by Shaptic**
Closes #502.

### CODE REVIEW

**Review by quietbits — APPROVED** [review]

File: types/index.d.ts [hunk 1]
```diff
@@ -747,7 +747,7 @@ export namespace Operation {
   ): xdr.Operation<RevokeClaimableBalanceSponsorship>;
 
   interface RevokeLiquidityPoolSponsorship extends BaseOperation<OperationType.RevokeSponsorship> {
-    balanceId: string;
+    liquidityPoolId: string;
```
Comment (leighmcculloch) [inline types/index.d.ts:750]: No test?

**Review by leighmcculloch — APPROVED** [review]
Looks fine, no test though?

File: types/index.d.ts (hunk 1 above)
Comment (Shaptic) [reply types/index.d.ts:750]: Yeahh.. unfortunately the entire set of operations doesn't have tests. This is a one-off fix but I have a long list of how we can get better TypeScript testing in this library (and better API testing in general...). Unfortunately, it's a behemoth of a task.
